global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sl-shape-generator'
    static_configs:
      - targets: ['sl-shape-api:3000']
    metrics_path: '/api/metrics'

  - job_name: 'nginx'
    static_configs:
      - targets: ['sl-shape-generator:80']
    metrics_path: '/nginx-status'
